// <auto-generated />
namespace BabyStore.Migrations.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class category_rowversion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category_rowversion));
        
        string IMigrationMetadata.Id
        {
            get { return "201709181212092_category_rowversion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
