// <auto-generated />
namespace BabyStore.Migrations.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addorders));
        
        string IMigrationMetadata.Id
        {
            get { return "201708291329169_addorders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
